/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;


import ConsultasSQL.QuerysMobiliarioyEquipo;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import Controlador.MobiliarioYEquipo;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Bucardo
 */
public class CrearMobiliarioyEquipo extends javax.swing.JFrame {
  private boolean hasValidFirstCharacter = false;
    /**
     * Creates new form CrearMobiliarioyEquipo
     */
    public CrearMobiliarioyEquipo() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.MONTH, 0); 
        //para que la fecha no sea mayor a la actual y menor que la actual
        fecha.setMaxSelectableDate(new Date());
        fecha.setMinSelectableDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCBestado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXAdescripcion = new javax.swing.JTextArea();
        txtnombre = new javax.swing.JTextField();
        btnG = new javax.swing.JButton();
        btbC = new javax.swing.JButton();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" Creación");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel1.setText("Nombre del Mobiliario :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel4.setText(" Estado :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel5.setText("Fecha de adquisición :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel7.setText("Descripción :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel8.setText("Crear mobiliario y equipo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jCBestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un estado", "nuevo", "usado", "mal estado", "inhabilitado" }));
        getContentPane().add(jCBestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 226, 30));

        TXAdescripcion.setColumns(20);
        TXAdescripcion.setLineWrap(true);
        TXAdescripcion.setRows(5);
        TXAdescripcion.setWrapStyleWord(true);
        TXAdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXAdescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(TXAdescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, 110));

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 226, 30));

        btnG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnG.setText("Guardar");
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });
        getContentPane().add(btnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        btbC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelarr.png"))); // NOI18N
        btbC.setText("Cancelar");
        btbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCActionPerformed(evt);
            }
        });
        getContentPane().add(btbC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 119, 60));

        fecha.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 226, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel2.setText("Cabtidad :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 220, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ListaodologoBarberia.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        // TODO add your handling code here:
        txtnombre.setText(txtnombre.getText().replaceAll("( )+", " "));
        if (txtnombre.getText().length() == 0 && evt.getKeyChar() == ' ') {
                    evt.consume();
                }      
        
        
         char c = evt.getKeyChar();
         if(Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();
         }
            int tam = txtnombre.getText().length();
        if(tam>=30){
            evt.consume();
        }  else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
                ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                ||(int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
                ||(int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=159
                ||(int)evt.getKeyChar()>=166 && (int)evt.getKeyChar()<=255){
             getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void TXAdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXAdescripcionKeyTyped
        // TODO add your handling code here:
          TXAdescripcion.setText(TXAdescripcion.getText().replaceAll("( )+", " "));
        if (TXAdescripcion.getText().length() == 0 && evt.getKeyChar() == ' ') {
                    evt.consume();
                }      
            int tam = TXAdescripcion.getText().length();
        if(tam>=250){
            evt.consume();
        }
        
          char c = evt.getKeyChar();
         if(Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();
         }
    }//GEN-LAST:event_TXAdescripcionKeyTyped

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
       // Obtener el carácter que se intenta agregar
        String currentText = txtcantidad.getText();
    char newChar = evt.getKeyChar();

    // Si el nuevo carácter es un dígito o una letra
    if (Character.isDigit(newChar)) {
       
        // Si el primer carácter es 0, no permitir ingresarlo
        if (currentText.isEmpty() && newChar == '0') {
            evt.consume(); // No permitir el ingreso del carácter
            return;
        }
        // Marcar que se ha ingresado al menos un carácter válido
        hasValidFirstCharacter = true;
    } else if (newChar == ' ' || newChar == '\b') {
        // Permitir espacios y teclas de retroceso (backspace)
        // Si aún no se ha ingresado ningún carácter válido y se intenta ingresar un espacio, no permitirlo
        if (!hasValidFirstCharacter && newChar == ' ') {
            evt.consume(); // No permitir el ingreso del carácter
            return;
        }
    } else {
        // Si no es un dígito, ni una letra, ni espacio, ni retroceso, no permitir ingreso
        evt.consume(); // No permitir el ingreso del carácter
        return;
    }
     // Comprobar si la longitud del texto supera el límite de 45 caracteres
    if (currentText.length() >= 2) {
        evt.consume(); // No permitir seguir escribiendo en el campo
    }    

    }//GEN-LAST:event_txtcantidadKeyTyped

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
           String nombre = txtnombre.getText().trim(); // Eliminar espacios en blanco al inicio y al final
        if (nombre.isEmpty()) {
          
            JOptionPane.showMessageDialog(this, "El nombre del mobiliario no puede estar vacío", "Error de validación", JOptionPane.INFORMATION_MESSAGE);
            return; // Salir del método si el campo está vacío
        }
         String cantidad = txtcantidad.getText().trim(); // Eliminar espacios en blanco al inicio y al final
 
          
       if (cantidad.isEmpty()) {
          JOptionPane.showMessageDialog(this, "La cantidad del mobiliario no puede estar vacío", "Error de validación", JOptionPane.INFORMATION_MESSAGE);
           
           return; // Salir del método si el campo está vacío
       }
     
            String estado = jCBestado.getSelectedItem().toString(); // que no este vacio, que solo seleccione 1
        if(estado.equals("Seleccione un estado")){
         JOptionPane.showMessageDialog(this, "No ha seleccionado ningun estado", "Error de validación", JOptionPane.INFORMATION_MESSAGE);
            return; // Salir del método si el campo está vacío
        }
         
         String fechas =((JTextField)fecha.getDateEditor().getUiComponent()).getText();
         Date fechaSeleccionada = fecha.getDate();
        if(fechas.isEmpty()){
            JOptionPane.showMessageDialog(null, "La fecha esta vacia","Error al guardar",
                    JOptionPane.WARNING_MESSAGE);
            return; // Salir del método si el campo está vacío
        }
       
        
          String descripcion =  TXAdescripcion.getText().trim(); // Eliminar espacios en blanco al inicio y al final
        if (descripcion.isEmpty()) {
              JOptionPane.showMessageDialog(this, "La descripción del mobiliario no puede estar vacía", "Error de validación", JOptionPane.INFORMATION_MESSAGE);
           
            return; // Salir del método si el campo está vacío
        }
     
        
          //crear una instancia de querysDepartamento
         QuerysMobiliarioyEquipo querys = new QuerysMobiliarioyEquipo();
         querys.setNombre(nombre);
         querys.setEstado(estado);
         querys.setCantidad(cantidad);
         querys.setDescripcion(descripcion);
         querys.setFechadeadquisicion(fechas);
         
         if (MobiliarioYEquipo.Guardar(querys)){
             JOptionPane.showMessageDialog(null, "Nuevo mobiliario se ha ingresado exitosamente","Guardado con éxito",
                     JOptionPane.INFORMATION_MESSAGE);
                MobiliarioYEquipo.MostrarMobiliarioyEquipo("");
                dispose();
         }else {
                JOptionPane.showMessageDialog(null, "Algo falló, consulte con el administrador de sistema", "Error al guardar", 
                    JOptionPane.OK_OPTION);
         }
        
        
    }//GEN-LAST:event_btnGActionPerformed

    private void btbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCActionPerformed
        // TODO add your handling code here:
         dispose();//cierra la ventana
    }//GEN-LAST:event_btbCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearMobiliarioyEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearMobiliarioyEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearMobiliarioyEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearMobiliarioyEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearMobiliarioyEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea TXAdescripcion;
    public static javax.swing.JButton btbC;
    public static javax.swing.JButton btnG;
    public static com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JComboBox<String> jCBestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtcantidad;
    public static javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
