/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.event.KeyEvent;
import ConsultasSQL.QuerysMobiliarioyEquipo;
import javax.swing.JOptionPane;
import Controlador.MobiliarioYEquipo;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Bucardo
 */
public class EditarMobiliarioyEquipo extends javax.swing.JFrame {

    /**
     * Creates new form EditarMobiliarioyEquipo
     */
    public EditarMobiliarioyEquipo() {
        initComponents();
        setLocationRelativeTo(null);
        txtid.setVisible(false);
        setResizable(false);
        
        fecha.setMaxSelectableDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jCBestado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdescripcion = new javax.swing.JTextArea();
        btnA = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edicion");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setText("Editar mobiliario y equipo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, 40));

        jLabel8.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel8.setText("Nombre del Mobiliario :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel4.setText("Estado :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 20));

        jLabel7.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel7.setText("Descripción :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        txtnombre.setEditable(false);
        txtnombre.setBorder(null);
        txtnombre.setFocusable(false);
        txtnombre.setRequestFocusEnabled(false);
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 203, -1));

        jCBestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione estado", "nuevo", "usado", "mal estado", "inhabilitado" }));
        getContentPane().add(jCBestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 228, -1));

        txtAdescripcion.setEditable(false);
        txtAdescripcion.setColumns(20);
        txtAdescripcion.setLineWrap(true);
        txtAdescripcion.setRows(5);
        txtAdescripcion.setWrapStyleWord(true);
        txtAdescripcion.setBorder(null);
        txtAdescripcion.setFocusable(false);
        txtAdescripcion.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(txtAdescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar2.png"))); // NOI18N
        btnA.setText("Actualizar");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        getContentPane().add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelarr.png"))); // NOI18N
        btnC.setText("Cancelar");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 120, 50));

        jLabel5.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel5.setText("Fecha de adquisición :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 20));

        fecha.setDateFormatString("yyyy-MM-dd");
        fecha.setEnabled(false);
        fecha.setFocusable(false);
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 230, -1));

        txtid.setEditable(false);
        txtid.setText("id");
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 28, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel2.setText("Cantidad :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 20));

        txtcantidad.setEditable(false);
        txtcantidad.setBorder(null);
        txtcantidad.setFocusable(false);
        txtcantidad.setRequestFocusEnabled(false);
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ListaodologoBarberia.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
        String estado = jCBestado.getSelectedItem().toString(); // que no este vacio, que solo seleccione 1
        if(estado.equals("seleccione estado")){
         JOptionPane.showMessageDialog(this, "No ha seleccionado ningun estado", "Error de validación", JOptionPane.INFORMATION_MESSAGE);
            return; // Salir del método si el campo está vacío
        }
        
            String fech =((JTextField)fecha.getDateEditor().getUiComponent()).getText();
       
            QuerysMobiliarioyEquipo querys = new QuerysMobiliarioyEquipo();
            querys.setNombre(txtnombre.getText());
            querys.setCantidad(txtcantidad.getText());
            querys.setEstado(estado);
            querys.setDescripcion(txtAdescripcion.getText());
            querys.setFechadeadquisicion(fech); //aqui fue un cambio
            querys.setId(Integer.parseInt(txtid.getText()));
            
             // Llamar al método Guardar de la clase Productos para guardar los datos
            if (MobiliarioYEquipo.Editar(querys)) {
               
                JOptionPane.showMessageDialog(null, "Se ha modificado exitosamente el mobiliario ", "Modificación exitosa", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                dispose();
                
               Controlador.MobiliarioYEquipo.MostrarMobiliarioyEquipo("");
                
            } else {
                
                   JOptionPane.showMessageDialog(null, "hay un error, consulte con el Administrador de Sistema", "Error de base de datos", 
                    JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btnAActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
         dispose();//cierra la ventana
    }//GEN-LAST:event_btnCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarMobiliarioyEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarMobiliarioyEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarMobiliarioyEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarMobiliarioyEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarMobiliarioyEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnA;
    public static javax.swing.JButton btnC;
    public static com.toedter.calendar.JDateChooser fecha;
    public static javax.swing.JComboBox<String> jCBestado;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea txtAdescripcion;
    public static javax.swing.JTextField txtcantidad;
    public static javax.swing.JTextField txtid;
    public static javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
