/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author Andrea
 */
public class MostrarMobiliarioyEquipo extends javax.swing.JPanel {

    private int paginaActual = 1;
    public static int totalPages ;
    
    public MostrarMobiliarioyEquipo() {
        initComponents();
        tblMostrarMobiliarioyEquipo.getTableHeader().setReorderingAllowed(false);
        Controlador.MobiliarioYEquipo.MostrarMobiliarioyEquipo("", paginaActual, totalPages, ListadoEstado.getModel().getSelectedItem().toString());
        PromptSupport.setPrompt("Buscar por el nombre", txtbusqueda);
    
        tblMostrarMobiliarioyEquipo.addMouseListener(new MouseAdapter(){
        public void mouseClicked(MouseEvent e){
            if (e.getClickCount()==2){
            int fila= tblMostrarMobiliarioyEquipo.getSelectedRow();
                    verMobiliarioyEquipo VerMobiliarioyEquipo = new verMobiliarioyEquipo();
                    
                    VerMobiliarioyEquipo.txtNombreMob.setText(tblMostrarMobiliarioyEquipo.getValueAt(fila, 1).toString());
                    VerMobiliarioyEquipo.txtCantidad.setText(tblMostrarMobiliarioyEquipo.getValueAt(fila, 2).toString());
                    VerMobiliarioyEquipo.txtEstado.setText(tblMostrarMobiliarioyEquipo.getValueAt(fila, 3).toString());
                    VerMobiliarioyEquipo.txtaDescripcion.setText(tblMostrarMobiliarioyEquipo.getValueAt(fila, 4).toString());
                    VerMobiliarioyEquipo.txtfecha.setText(tblMostrarMobiliarioyEquipo.getValueAt(fila, 5).toString());
                    VerMobiliarioyEquipo.setVisible(true);
            }
        }
        
        });
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarMobiliarioyEquipo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Previo = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        seguimiento = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        ListadoEstado = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel1.setBackground(new java.awt.Color(253, 253, 253));

        tblMostrarMobiliarioyEquipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblMostrarMobiliarioyEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Núm.", "Nombre", "Cantidad", "Estado", "Descripción", "Fecha de adquisición", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMostrarMobiliarioyEquipo);
        if (tblMostrarMobiliarioyEquipo.getColumnModel().getColumnCount() > 0) {
            tblMostrarMobiliarioyEquipo.getColumnModel().getColumn(0).setMinWidth(50);
            tblMostrarMobiliarioyEquipo.getColumnModel().getColumn(0).setMaxWidth(50);
            tblMostrarMobiliarioyEquipo.getColumnModel().getColumn(2).setMinWidth(75);
            tblMostrarMobiliarioyEquipo.getColumnModel().getColumn(2).setMaxWidth(75);
            tblMostrarMobiliarioyEquipo.getColumnModel().getColumn(3).setMinWidth(150);
            tblMostrarMobiliarioyEquipo.getColumnModel().getColumn(3).setMaxWidth(150);
            tblMostrarMobiliarioyEquipo.getColumnModel().getColumn(4).setMinWidth(0);
            tblMostrarMobiliarioyEquipo.getColumnModel().getColumn(4).setMaxWidth(0);
            tblMostrarMobiliarioyEquipo.getColumnModel().getColumn(5).setMinWidth(150);
            tblMostrarMobiliarioyEquipo.getColumnModel().getColumn(5).setMaxWidth(150);
            tblMostrarMobiliarioyEquipo.getColumnModel().getColumn(6).setMinWidth(0);
            tblMostrarMobiliarioyEquipo.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ListaodologoBarberia.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Listado de mobiliario y equipo");

        btnAgregar.setBackground(new java.awt.Color(255, 255, 248));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 255, 248));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.jpg"))); // NOI18N
        jLabel3.setText("Buscar");

        Previo.setBackground(new java.awt.Color(255, 255, 248));
        Previo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_atras.png"))); // NOI18N
        Previo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevioActionPerformed(evt);
            }
        });

        siguiente.setBackground(new java.awt.Color(255, 255, 248));
        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_delante.png"))); // NOI18N
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        seguimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        seguimiento.setText("Página :");

        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyReleased(evt);
            }
        });

        ListadoEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListadoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nuevo", "Usado", "Mal estado", "Inhabilitado" }));
        ListadoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ListadoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(jLabel2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Previo)
                        .addGap(18, 18, 18)
                        .addComponent(siguiente)
                        .addGap(18, 18, 18)
                        .addComponent(seguimiento)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(65, 65, 65)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnEditar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ListadoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(siguiente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Previo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(seguimiento)
                        .addGap(16, 16, 16)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        EditarMobiliarioyEquipo mostradatos = new EditarMobiliarioyEquipo();
         
          int fila = tblMostrarMobiliarioyEquipo.getSelectedRow();  
        
        if (fila>=0){
            
        mostradatos.txtid.setText(tblMostrarMobiliarioyEquipo.getValueAt(fila, 0).toString());   // aqui se agrego esto
        mostradatos.txtnombre.setText(tblMostrarMobiliarioyEquipo.getValueAt(fila, 1).toString());
        mostradatos.txtcantidad.setText(tblMostrarMobiliarioyEquipo.getValueAt(fila, 2).toString());
        mostradatos.jCBestado.setSelectedItem(tblMostrarMobiliarioyEquipo.getValueAt(fila, 3).toString());
        mostradatos.txtAdescripcion.setText(tblMostrarMobiliarioyEquipo.getValueAt(fila, 4).toString());
        try{
                String fechaString = tblMostrarMobiliarioyEquipo.getValueAt(fila, 5).toString();
                SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
                Date fechas = sdf.parse(fechaString);
                EditarMobiliarioyEquipo.fecha.setDate(fechas);
            }catch(ParseException e){
                e.printStackTrace();
            }
      
       //ediFormProv.tfI.setText(tblMostrarProveedores.getValueAt(fila, 0).toString());
       mostradatos.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No ha selecionado ningun mobiliario  para editar", "Error al seleccionar el mobiliario", JOptionPane.INFORMATION_MESSAGE);
         }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void PrevioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevioActionPerformed
        if (paginaActual > 1) {
            paginaActual--;
            Controlador.MobiliarioYEquipo.MostrarMobiliarioyEquipo(txtbusqueda.getText(), paginaActual, totalPages,ListadoEstado.getModel().getSelectedItem().toString());
        }
    }//GEN-LAST:event_PrevioActionPerformed

    private void ListadoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoEstadoActionPerformed
        String  valor= ListadoEstado.getModel().getSelectedItem().toString();
    
        Controlador.MobiliarioYEquipo.MostrarMobiliarioyEquipo(txtbusqueda.getText(), paginaActual, totalPages,valor);
    }//GEN-LAST:event_ListadoEstadoActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        totalPages = Controlador.MobiliarioYEquipo.NumeroPages(txtbusqueda.getText(), paginaActual,ListadoEstado.getModel().getSelectedItem().toString());
        if (paginaActual < totalPages) {
            paginaActual++;
            Controlador.MobiliarioYEquipo.MostrarMobiliarioyEquipo(txtbusqueda.getText(), paginaActual, totalPages,ListadoEstado.getModel().getSelectedItem().toString());
        }
    }//GEN-LAST:event_siguienteActionPerformed

    private void txtbusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyReleased
        String textoBusqueda = txtbusqueda.getText();
          Controlador.MobiliarioYEquipo.MostrarMobiliarioyEquipo(textoBusqueda, paginaActual, totalPages,ListadoEstado.getModel().getSelectedItem().toString());
    }//GEN-LAST:event_txtbusquedaKeyReleased

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        CrearMobiliarioyEquipo mobiliario = new CrearMobiliarioyEquipo();
                mobiliario.setVisible(true);
                mobiliario.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> ListadoEstado;
    public static javax.swing.JButton Previo;
    public static javax.swing.JButton btnAgregar;
    public static javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel seguimiento;
    public static javax.swing.JButton siguiente;
    public static javax.swing.JTable tblMostrarMobiliarioyEquipo;
    private javax.swing.JTextField txtbusqueda;
    // End of variables declaration//GEN-END:variables
}
